services:

  mysql:
    image: mysql:8.0.34
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=TBank
      - MYSQL_USER=nata
      - MYSQL_PASSWORD=qwerty999
    volumes:
      - ./db_mysql:/var/lib/mysql
  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./db_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=TBank
      - POSTGRES_USER=nata
      - POSTGRES_PASSWORD=qwerty999
  node-app:
    build: ./gate-simulator
    image: node-app:1.0
    ports:
      - '9999:9999'